### ISSUE TITLE
Decision count in dropdown is incorrect after toggling decision a few times

### ISSUE THREAD

**Issue by JeffreyATW** [labzero/lunch#50]

**Comment by Humuhumu** [comment]
It appears that when one location is marked as the decision, and then another location is marked instead, the decision counts are not being updated.

To recreate:

- Mark one location as the decision
- Mark a different location as the decision
- Decision count is still 1 on the first decision
- Mark first location as the decision again
- Decision count is now 2 on the first location, and 1 on the second location

**Comment by Humuhumu** [comment]
Problem:

When a decision is changed, the DECISION_POSTED action increments the state's all_decision_count property for that restaurant, which came from the db on initial state load. When a decision is directly removed from a restaurant, the all_decision_count property is decremented by the DECISION_DELETED action. However, when a decision is _changed_, the removal of the first decision happens indirectly, and there is no (current) way to know which restaurants previously had this value incremented and thus now need it decremented. 

Proposal:

Rather than incrementing and decrementing the all_decision_count value, we will instead calculate the display value based on the property from the db + whether this restaurant is the one currently in the state's decision. Also remove the incrementing and decrementing actions on all_decision_count currently in reducerMaps.js.

Create a new selector in selectors/index.js called makeGetAllDecisionCountForRestaurant that will return this calculated value.

**Comment by JeffreyATW** [comment]
@nyscherm If you're working on this, you might benefit from taking a look at the commits in this branch, if you haven't already: https://github.com/labzero/lunch/tree/feature/50-decision-count-bug
